//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PackageManager.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PackageManager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;#
        ///.SYNOPSIS
        ///    Creates a manifest describing a file or the contents of a directory based on file names, sizes, and md5 hashes
        ///.PARAMETER Target
        ///    Target to generate a manifest for. If a file, will provide a manifest describing that file. If a directory, will provide a manifest describing the contents of the directory.
        ///.PARAMETER Format
        ///    Format of output.
        ///.PARAMETER Recurse
        ///    Whether to create manifests of contained directories recursively.
        ///#&gt;
        ///[CmdletBinding()]
        ///param(
        ///    [Parameter(Mand [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Get_Md5Manifest {
            get {
                return ResourceManager.GetString("Get_Md5Manifest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;PACKAGE_NAME&quot;: &quot;20190712-ExamplePackage&quot;, 
        ///  &quot;DATE&quot;: &quot;07-11-19&quot;, 
        ///  &quot;BUSINESS_ITEM&quot;: &quot;Story 1232&quot;, 
        ///  &quot;PREREQUISITES&quot;: [
        ///      &quot;NCRDiag v5.03.028 or later&quot;, 
        ///      &quot;Ingenico TeliumOPOS Driver (firmware 18+) or later&quot;
        ///    ], 
        ///  &quot;PACKAGE_DESCRIPTION&quot;: &quot;This package is to install a new form that will fix an issue with the CDU doing something that it should not have been doing, so we will make sure it doesn&apos;t do that any more. We are really determined to not let this issue exist in the future, so t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string sample_input {
            get {
                return ResourceManager.GetString("sample_input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Echo Off
        ///setLocal enableDelayedExpansion
        ///
        ///:: updates the modified timestamp of the specified file
        ///
        ///set ERRLEV=0
        ///set TARGET_FILE=%~nx1
        ///set TARGET_DIR=%~dp1
        ///
        ///if not exist &quot;%TARGET_DIR%%TARGET_FILE%&quot; (
        ///    echo:ERR: file %TARGET_DIR%%TARGET_FILE% does not exist; please provide full path 1&gt;&amp;2
        ///    goto :ERR
        ///)
        ///
        ///
        ///pushd &quot;%TARGET_DIR%&quot;
        ///
        ///copy /b &quot;%TARGET_FILE%&quot;+,, &gt; nul
        ///set ERRLEV=%ERRORLEVEL%
        ///popd
        ///if not &quot;%ERRLEV%&quot;==&quot;0&quot; goto :ERR
        ///
        ///goto :END
        ///
        ///goto :END
        ///
        ///:ERR
        ///if &quot;%ERRLEV%&quot;==&quot;0&quot; set ERRLEV=1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string touch {
            get {
                return ResourceManager.GetString("touch", resourceCulture);
            }
        }
    }
}
